#!/usr/bin/env ruby

ignored = [
  "*.tm_properties*", 
  "*.DS_Store*", 
  "*.git*",
  "*.sass-cache*", 
  "*.svn*",
  "*assets*",
  "*branches*",
  "*coffeescript*", 
  "*php/includes*", 
  "*node_modules*", 
  "*scss*", 
  "*tags*",
  "*tmp*",
  "*trunk*",
  "cta.js*",
  "Gruntfile.js*", 
  "latest.zip", 
  "package.json*", 
  "zipper"
].map{ |i| "-x '../lively-chat-support/#{i}'" }.join(" ")

debug_true = "const debug = true;"
debug_false = "const debug = false;"
show_errors = "*/\n\nini_set(\"display_errors\",1);\nini_set(\"display_startup_errors\",1);\nerror_reporting(-1);"
hide_errors = "ini_set(\"display_errors\",1);\nini_set(\"display_startup_errors\",1);\nerror_reporting(-1);\n\n*/"

File.open("lively-chat-support.php") { |file|
  contents = file.read.gsub debug_true, debug_false
  contents = contents.gsub show_errors, hide_errors
  File.open("lively-chat-support.php", "w") { |f| f << contents }
}

`zip -r lively-chat-support.zip ../lively-chat-support #{ignored}`
`rm -rf trunk`
`rm -rf lively-chat-support`
`unzip lively-chat-support.zip`
`mv lively-chat-support trunk`

File.open("lively-chat-support.php") { |file|
  contents = file.read.gsub debug_false, debug_true
  contents = contents.gsub hide_errors, show_errors
  File.open("lively-chat-support.php", "w") { |f| f << contents }
}